# Generated by Django 4.1.3 on 2022-12-04 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_vote',
            field=models.ManyToManyField(blank=True, related_name='user_vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='vote',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
